services:
  onefilelinux-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: onefilelinux-builder-local:latest
    container_name: onefilelinux-builder
    # Run as root by default in GitHub Actions
    user: ${RUN_AS_USER:-root}
    volumes:
      # Mount source code including all library scripts
      - ../build:/onefilelinux/build:rw
      # Mount output directory
      - ../output:/onefilelinux/output:rw
      # Mount persistent build cache
      - onefilelinux-cache:/onefilelinux/.buildcache
    environment:
      # Configure build arguments here (can be overridden with .env)
      - BUILD_ARGS=${BUILD_ARGS:-"--with-zfs --with-recovery-tools --with-network-tools --use-cache --make-verbose"}
      # Configure user ID mapping (only used if not running as root)
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      # Explicitly run as root in container
      - RUN_AS_ROOT=true
      # Build optimization
      - USE_CACHE=true
      - CCACHE_COMPRESS=true
      # Timing and performance logging
      - FINALIZE_TIMING_LOG=true
      - TIMING_LOG_FILE=/onefilelinux/build/build_timing.log
      # Password settings
      - GENERATE_RANDOM_PASSWORD=${GENERATE_RANDOM_PASSWORD:-true}
      - ROOT_PASSWORD=${ROOT_PASSWORD:-"onefilelinux"}
    # Resource limits (dynamically set by auto-resources.sh script)
    deploy:
      resources:
        limits:
          memory: ${DOCKER_MEMORY:-"4g"}
          cpus: ${DOCKER_CPUS:-2}
    # Enable any required capabilities
    cap_add:
      - SYS_ADMIN  # Required for chroot operations
    # Enable privileged mode for complex operations like loop devices
    privileged: true

volumes:
  onefilelinux-cache:
    driver: local