name: Docker Build

on:
  push:
    branches: [ master, main, dev ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (minimal, standard, full)'
        required: true
        default: 'standard'
        type: choice
        options:
          - minimal
          - standard
          - full

jobs:
  # Job to determine which builds to run based on trigger type
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # For manual triggers, only build the selected type
            echo "matrix={\"include\":[{\"name\":\"${{ github.event.inputs.build_type }}\",\"build_args\":\"${{ github.event.inputs.build_type == 'minimal' && '--minimal' || github.event.inputs.build_type == 'full' && '--full' || '--with-zfs --with-recovery-tools --with-network-tools' }} --compression-tool=upx\"}]}" >> $GITHUB_OUTPUT
          else
            # For automatic triggers, build all types with UPX compression
            echo "matrix={\"include\":[{\"name\":\"minimal\",\"build_args\":\"--minimal --compression-tool=upx\"},{\"name\":\"standard\",\"build_args\":\"--with-zfs --with-recovery-tools --with-network-tools --compression-tool=upx\"},{\"name\":\"full\",\"build_args\":\"--full --compression-tool=upx\"}]}" >> $GITHUB_OUTPUT
          fi

  # Build job using the unified build script
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
      fail-fast: false
    
    name: Build OneRecovery (${{ matrix.name }})
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ make autoconf automake libtool libelf-dev upx-ucl unzip zstd xz-utils ccache uuid-dev libuuid1 libblkid-dev
          
          # List checkout directory contents
          echo "Current directory: $(pwd)"
          ls -la
          
          # Create build directory with appropriate permissions
          mkdir -p build output
          # Ensure we have complete ownership of the source directory
          sudo chown -R $USER:$USER .
          sudo chmod -R 777 build output
          
          # Create critical directories with proper permissions
          mkdir -p build/output build/scripts
          sudo chmod -R 777 build/output build/scripts
          
          # Show the directory structure after setup
          find . -type d -maxdepth 2 | sort
      
      - name: Make build scripts executable
        run: |
          # Make all library scripts executable
          chmod +x build/80_common.sh
          chmod +x build/81_error_handling.sh
          chmod +x build/82_build_helper.sh
          chmod +x build/83_config_helper.sh
          chmod +x build/85_cross_env_build.sh
          
          # Make all build scripts executable
          chmod +x build/00_prepare.sh
          chmod +x build/01_get.sh
          chmod +x build/02_chrootandinstall.sh
          chmod +x build/03_conf.sh
          chmod +x build/04_build.sh
          chmod +x build/99_cleanup.sh
          chmod +x build/build.sh
          
          # Make tool scripts executable
          mkdir -p build/tools
          if [ -d "build/tools" ]; then
            chmod +x build/tools/*.sh 2>/dev/null || true
          fi
      
      - name: Cache Alpine kernel configs
        uses: actions/cache@v4
        with:
          path: build/zfiles/kernel-configs
          key: alpine-kernel-config-${{ hashFiles('build/80_common.sh') }}
          restore-keys: |
            alpine-kernel-config-
      
      - name: Set up ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ matrix.name }}-
            ccache-${{ runner.os }}-
            
      - name: Fix potential PATH issues
        run: |
          echo "Checking shell and PATH configuration..."
          echo $SHELL
          echo $PATH
          which mkdir
          which bash
          which sh
          sudo ln -sf /bin/mkdir /usr/local/bin/mkdir || true
          mkdir --help

      - name: Run unified build script
        env:
          GITHUB_ACTIONS: "true"
          USE_ALPINE_KERNEL_CONFIG: "true"
          AUTO_KERNEL_CONFIG: "true"
          USE_CACHE: "true"
          CACHE_DIR: "~/.ccache"
          CCACHE_DIR: "~/.ccache"
          PATH: "/usr/lib/ccache:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
        run: |
          # Ensure we're using a proper shell with full PATH
          /bin/bash -c 'echo "Current path: $PATH"'
          /bin/bash -c 'which mkdir'
          /bin/bash -c 'mkdir -p output'
          
          # Configure ccache
          /bin/bash -c 'ccache --max-size=5G'
          /bin/bash -c 'ccache -z'  # Zero statistics
          
          # Prepare a clean .config file for the kernel
          echo "Setting up a clean minimal kernel configuration"
          # First make sure build directory exists
          mkdir -p build
          cd build || true
          # Make sure build directory is writable
          sudo chmod -R 777 . || true
          if [ -d "linux" ]; then
            sudo rm -f linux/.config || true
            sudo rm -rf linux/include/config || true
            sudo touch linux/.config || true
            sudo chmod 777 linux/.config || true
          fi
          
          # Return to main directory and ensure build scripts are accessible
          cd ..
          ls -la build/
          
          # Build with minimal configuration to reduce complexity
          /bin/bash -c 'cd build && pwd && ls -la && chmod +x *.sh && ./85_cross_env_build.sh ${{ matrix.build_args }} --minimal-kernel --use-cache --use-swap --make-verbose'
      
      - name: Check for build artifacts
        id: check_files
        run: |
          /bin/bash -c 'if [ -f "./output/OneRecovery.efi" ]; then
            echo "efi_file=true" >> $GITHUB_OUTPUT
            du -h ./output/OneRecovery.efi
            
            # Display ccache statistics
            echo "CCache Statistics:"
            ccache -s
          else
            echo "efi_file=false" >> $GITHUB_OUTPUT
            echo "Build failed to produce OneRecovery.efi"
            exit 1
          fi'
      
      - name: Upload build artifact
        if: steps.check_files.outputs.efi_file == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: OneRecovery-${{ matrix.name }}
          path: ./output/OneRecovery.efi
          if-no-files-found: error

  # Package all artifacts into a release
  release:
    needs: build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Create release package
        run: |
          /bin/bash -c 'mkdir -p release
          # Only copy files that exist
          if [ -f "./artifacts/OneRecovery-minimal/OneRecovery.efi" ]; then
            cp ./artifacts/OneRecovery-minimal/OneRecovery.efi ./release/OneRecovery-minimal.efi
          fi
          if [ -f "./artifacts/OneRecovery-standard/OneRecovery.efi" ]; then
            cp ./artifacts/OneRecovery-standard/OneRecovery.efi ./release/OneRecovery-standard.efi
          fi
          if [ -f "./artifacts/OneRecovery-full/OneRecovery.efi" ]; then
            cp ./artifacts/OneRecovery-full/OneRecovery.efi ./release/OneRecovery-full.efi
          fi
          cd release
          zip -r OneRecovery-release.zip *.efi'
      
      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: OneRecovery-release
          path: ./release/OneRecovery-release.zip